<?php

function d8_angular_toh_theme($existing, $type, $theme, $path) {
    return array(
        'd8_angular_toh' => array(
            'variables' => array(
                'base_href'=>NULL,
                'content' => NULL
            )
        ),
    );
}

function template_preprocess_d8_angular_toh(&$vars){
    $vars['#attached']['library'][] = 'd8_angular_toh/d8_angular_toh';
    $vars['#attached']['drupalSettings']['d8_angular_toh'] = array(
        'module_path'=>drupal_get_path('module', 'd8_angular_toh')
    );
}